"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
# import django

# django.setup()


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e84)f1*014u+zp_z)b(ou+j^s@naz4r2!wspiv8j_^o2xo%1dz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    # Apps
    'users',
    'dashboard',
    'training',
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Rest
    'rest_framework',
    'rest_framework.authtoken',
    # drf-social-oauth2
    'oauth2_provider',
    'social_django',
    'drf_social_oauth2',
    # CORS
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.AllowAny'
        'rest_framework.permissions.IsAuthenticated'
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'drf_social_oauth2.authentication.SocialAuthentication',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # cors
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.UserExtended'

AUTHENTICATION_BACKENDS = (
    'drf_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
from django.core.files.storage import FileSystemStorage

MEDIA_PHOTO_VIDEOS_PATH = FileSystemStorage(location='/media/photos_videos')

CORS_ORIGIN_ALLOW_ALL = True

# On production
# CORS_ORIGIN_WHITELIST = ('http://localhost:3000',)

# CORS_ALLOWED_ORIGINS = ['*']

JITSI_PRIVATE_KEY = b"""-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEAqf8UfMivTCXa42TmBYJy+ZPn5YGtrO9dgXVUKUETnDob7m3l
CnnhB7437MzGI2Caz4sOHi0gRnn/byhCIcTIsnrNGc4UL8nPtcO/86gi/K4zf/Ap
8hSjvONN6flV11x4SIFtzkVGoZfhWGBZ/4a/3byUIqZJ5IyRN5ogzsT4Tk1HL4gy
+BvItVEPfJuGoPHIBx8MVojamYrog2V73vhHvzQ1cg6JwzKSQXvc1QsBh8jSZTqw
pja7x3Hlfqiw8EWUQIh88LjBtJFx4404VNkgJgAAmt9XjBZiT6GlCRQ889loHtza
sUxkbHPmgfCtk66Rqz0KcGyUJNNQPgPRgg22V8ehyYlACC8Yg0yo7IlwZe4RVs6A
X9tTA7/m+5zR3mmA7j/aO+kN5nV+ymyAh9JVO7LCEVVPxxBXRJnJdG1v0Jq1C3Yr
bjEJskV1tXDDc6n48XuehoHmixqWX+imCVtxrIzZ4sd/BIdWaNFJypND4mzuJY+P
z3FaXFk7iZ4bxNauXx/svvxF5v+eiCzzk8mQeIF71bVn5gd7RhqnSWK8qU7+sEXQ
hcBW9BVsotwJnlawJCw38G6sfjCzENKRHYdgNNyfxDir/guNcW1UML32dNSRhF5/
GWxaWzqd5tOd+RR56t5UsaCOnAODZs7NgTE3fFw8VGBZP/JKqpEKHsqcr18CAwEA
AQKCAgEAqA0NIMp3WMy3VUJCjkHGDWmkvmJy4VmD0128hEfb7f4X7J1g5flUdwYZ
XROV8BUpFXC+1SABHwqtdCKVNbLGQIJbTV5G4HMdze8kS+f0JlzDdn9hx/mVYD5I
oLsmnA7CrdKdTWN4jniJgYdGkO+Rrs8klhhTRgeb6x6HvkBDw4xridaXpGQ7BtuK
dsF81pAOENQlq0oA5/bFIlfpm6NPsfoXt5gdogTVRrz+svD9Y1EohH//b2D+Qw0a
NRroR65Q/3auJH5Qp4N81dmeTWqTeF1aO7/8WPUr3NLMRmxmUR2j65ai7tC5Gel9
fwkBXtQdFu3x6u+7h6gKVDQMIggSL5lpIUT0oJUCAm4iP91jVzl6ETXKPRCR6pmD
6X6bQ6RFp0Nzzr3vELETuq/mE+FZ02nFqwtzZaodeVwscmwESU8Y0r6qrtaaU9UI
YsErPSmGyBOZoGYyCO5Sl14l9hz6fJ9zit1OU0fUBb4RO6fuXXx1uk5bRdH4GaKs
t/XnmeLbMkBo7EIuK3U+tits0TF6vxcPyDwv5NkN/L/uA1VdHUuzuE6xR0f7FUux
ZmtDZfy5ISlyRs0+MZMhtdM7oJGAV6iWY3LcEya5UsfXQN94AqguyMuvvzDNp0iu
E9WOLNss/c0yyR8phBMgtYQbPfivMS+D4ZYX+0gRNBsUJNl7TZkCggEBAN2enAsZ
N9VB8OcK6k6zPxoKTxovOjDqyHtAPGaTtsw6XI3X6HJZEVU3wob9mNfRzww9x9EW
b0umhtSzIArJ8Wm7epEiOcQZwo+H+MSC6xrgjf94PcQ/uz5kts6N+mgy0s893p1W
TL8Djpi54QhT99NP3oFRbxh4ll/w0GiEohJKii1wD6P/nKgvn8UIrQ/VvcTtgEvf
LNiMsFFEiHngIQpN4U2a/crmPDuHpg/4v5U4clDPIVZXruA5awi7/y2AXWsYU/o7
2bvAfe9hiIq0ZjVO5q/wM76V0IuZbqCh5sbLw3GguLLeLl2H/rhJbSVW6v1DujOw
8j40etSYOZ6UwCUCggEBAMReT3Jojyt/ZehOszDaBKxHcXns22JELqA7LXpWoPjO
EZohZCjQIFs+IRaWwjQVJ0HjyyFTjFLxzqnd4aJy1IdlSDTgX3SMCPyFDZp7jOYG
yWHlxf9NdU3jyZJalVN1wMWeSHswm0bEfyYDq4BAolhkOXBRvtcbKEMWRyEx5slx
iO55xijsUnnRVvtNIH5zWlWyhPzCV7rbIxTd1L6EMST3+zIxmHh9x8rCAVWtrUmc
6Nq+bFXc138WvnYTnWZ2w9pH3znmVx+qpZ7zLgQNDm1/lRPp5g1PO1+j3gxW/uqb
cLHizJ0V9nqs6s0josydT7kxgY+rbHUEK9rOeh4wSDMCggEAe8UODuC5nt9h5Bbj
fqp6rlddkBkaHaGx76uTUBJk/7AEaq9PQTVfCcHHYU6WIsopIQQL6UjnRU+uc3HK
jlvz+IHc1NtReaSNVU2x8EXRecQ5aZjEniqdrx3ePoNqevEPbPB3uFUvLWqWI9OD
yvviJ2Cuung5XGhUSyaZrhWM0jxQ6UlxYrzpx8A5MXhD9tj/T9D4Wuc8C4CfI/Pr
aG105mVSU94gqUVmFDUQ2FCq5nKM3XagfrEfmFhY35rmy4mqIpqGo/TzB/lcG+nT
sOtJPbJgAZhbva+7tYsuDoX89b9s2rPREwwkxtWhu1g+naDqQiGmByJmV7lFdB/D
5j3bBQKCAQEApaBaaEhSwcCBxvBiaYjqOhlEWC90VyzlGtbvI+nfehvtctBJN7dc
IzmDFRdxlBZnd0bYNTLP/8Heqx3vy2IJam39+kNpn9bhWYQsFimxjO8aeo0gdJbz
ow/HG791heCjCMvZnLZBse3YxMqBo/pgNCfM3rTEP5CzY+ptck0xuKUfdu2VOz0g
z4jHUc0a5C0Ne4zIaJzO/FcK/vWgFFVRUjorUInObYrBsn3yPD7yE03ahW3p2H4d
8R7Q5KzkrODtjrXiTWbAA4CekzPPkzEkAy2CIzq8hGtYy/FeP5A9EMqswg1mwfQd
YhlpLj+pd+YTsUNVYUWYhBZRmwteqwnUSwKCAQEAvdPql2sthSYgAYY+OmQUfkai
Ntf/NeWEiWSuT2QDZwNyCF7F+4lBx4dBK90Srg9GVU3C5i/VsBO6bUXI9nSUgD2E
3hUO09NsooJPFeM9GlrcscsdwgGWJbNOkblQGy405BQ5qzB8MKAL2NBkNcdSbzeq
X+wrydvb5e0ZrlpMWTO70zGyo7wqF1IrHo9AQ3OE36IF71nD85pRV17KOQgpXnWt
8+Y4/jIWU3YrL7EVmZ+ZRvqzOLpd/S0WBEvCHm4JuGctQ994bBsVCMsGLyREeFqL
0ZnNEf31v6VvWG4uoYl3prjD3KJt9iKt0jzpfGbSXKfrkyjG4DbyHlnI7ZlQag==
-----END RSA PRIVATE KEY-----"""

JITSI_PUBLIC_KEY = b"""-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqf8UfMivTCXa42TmBYJy
+ZPn5YGtrO9dgXVUKUETnDob7m3lCnnhB7437MzGI2Caz4sOHi0gRnn/byhCIcTI
snrNGc4UL8nPtcO/86gi/K4zf/Ap8hSjvONN6flV11x4SIFtzkVGoZfhWGBZ/4a/
3byUIqZJ5IyRN5ogzsT4Tk1HL4gy+BvItVEPfJuGoPHIBx8MVojamYrog2V73vhH
vzQ1cg6JwzKSQXvc1QsBh8jSZTqwpja7x3Hlfqiw8EWUQIh88LjBtJFx4404VNkg
JgAAmt9XjBZiT6GlCRQ889loHtzasUxkbHPmgfCtk66Rqz0KcGyUJNNQPgPRgg22
V8ehyYlACC8Yg0yo7IlwZe4RVs6AX9tTA7/m+5zR3mmA7j/aO+kN5nV+ymyAh9JV
O7LCEVVPxxBXRJnJdG1v0Jq1C3YrbjEJskV1tXDDc6n48XuehoHmixqWX+imCVtx
rIzZ4sd/BIdWaNFJypND4mzuJY+Pz3FaXFk7iZ4bxNauXx/svvxF5v+eiCzzk8mQ
eIF71bVn5gd7RhqnSWK8qU7+sEXQhcBW9BVsotwJnlawJCw38G6sfjCzENKRHYdg
NNyfxDir/guNcW1UML32dNSRhF5/GWxaWzqd5tOd+RR56t5UsaCOnAODZs7NgTE3
fFw8VGBZP/JKqpEKHsqcr18CAwEAAQ==
-----END PUBLIC KEY-----"""
