# Generated by Django 3.2.7 on 2021-10-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('difficulty', models.CharField(choices=[('0', 'Easy'), ('1', 'Medium'), ('2', 'Hard'), ('3', 'Armagedon')], default='1', max_length=1)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
