# Generated by Django 3.2.7 on 2021-10-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_traininggroup_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='training.traininggroup'),
        ),
    ]
