# Generated by Django 3.2.7 on 2021-10-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_training_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='ping',
            field=models.IntegerField(default=-1),
        ),
    ]
