# Generated by Django 3.2.7 on 2021-10-30 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_training_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ping',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
