# Generated by Django 3.2.7 on 2021-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_training_ping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='ping',
            field=models.IntegerField(default=0),
        ),
    ]
